### ISSUE TITLE
OSError: libcusparse.so.10.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by arilwan** [Xtra-Computing/thundergbm#59]
Trying to work with ThunderGBM on Ubuntu. Installation seems to be successful:
```
$ pip install thundergbm
Requirement already satisfied: thundergbm in ./venv/lib/python3.8/site-packages (0.3.16)
Requirement already satisfied: numpy in ./venv/lib/python3.8/site-packages (from thundergbm) (1.21.4)
Requirement already satisfied: scipy in ./venv/lib/python3.8/site-packages (from thundergbm) (1.7.2)
Requirement already satisfied: scikit-learn in ./venv/lib/python3.8/site-packages (from thundergbm) (1.0.1)
Requirement already satisfied: joblib>=0.11 in ./venv/lib/python3.8/site-packages (from scikit-learn->thundergbm) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in ./venv/lib/python3.8/site-packages (from scikit-learn->thundergbm) (3.0.0)

```
But them working with it generates error:

```
>>> from thundergbm import TGBMClassifier
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/Desktop/gpuimlearn/src/CPU-imLearn/venv/lib/python3.8/site-packages/thundergbm/__init__.py", line 10, in <module>
    from .thundergbm import *
  File "~/Desktop/gpuimlearn/src/CPU-imLearn/venv/lib/python3.8/site-packages/thundergbm/thundergbm.py", line 32, in <module>
    thundergbm = CDLL(lib_path)
  File "~/anaconda3/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcusparse.so.10.0: cannot open shared object file: No such file or directory

```
Ubuntu distribution:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:    18.04
Codename:   bionic
```

**Comment by zeyiwen** [comment]
You can build the wheel file from [this link](https://github.com/Xtra-Computing/thundergbm/blob/master/docs/how-to.md#how-to-build-the-python-wheel-file-for-linux).
